### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [rhklite/palenight_zsh_theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by rhklite** [comment]
@unixorn license added :)

**Comment by unixorn** [comment]
Thanks! Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/763
